#!/usr/bin/env python3
"""Generate Urban RAG corpus ledger artifacts.

Reconciles the legacy visual corpus (`data/page_images` +
`data/embeddings/metadata.json`) with the current ingest pipeline state
(`data/docs/*`). Writes:

- docs/corpus_ledger.json
- docs/corpus_ledger.md
"""

from __future__ import annotations

import collections
import json
import re
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
ACTIVE_LEGACY_PREFIXES = ["urdpfi_vol1", "urdpfi_vol2", "swm_2016"]


def _count_lines(path: Path) -> int:
    if not path.exists():
        return 0
    with path.open("rb") as f:
        return sum(1 for _ in f)


def _image_prefix_counts(image_dir: Path) -> collections.Counter[str]:
    counts: collections.Counter[str] = collections.Counter()
    for image in image_dir.glob("*.png"):
        match = re.match(r"(.+)__page_(\d+)\.png$", image.name)
        if match:
            counts[match.group(1)] += 1
    return counts


def _metadata_prefix_counts(
    metadata_path: Path,
) -> tuple[list[dict[str, Any]], collections.Counter[str]]:
    if not metadata_path.exists():
        return [], collections.Counter()
    rows = json.loads(metadata_path.read_text())
    counts: collections.Counter[str] = collections.Counter()
    for row in rows:
        source = str(row.get("source", "")).removesuffix(".pdf")
        counts[source] += 1
    return rows, counts


def _first_doc_title(parsed_path: Path) -> str:
    if not parsed_path.exists():
        return "source.pdf"
    try:
        parsed = json.loads(parsed_path.read_text())
    except Exception:
        return "source.pdf"

    sections = parsed.get("sections") or []
    title = (sections[0].get("title") if sections else None) or "source.pdf"

    if title != "source.pdf":
        return str(title)[:110]

    for page in parsed.get("pages", [])[:3]:
        for element in page.get("elements", [])[:5]:
            text = str(element.get("text") or "").strip().replace("\n", " ")
            if text:
                return text[:110]
    return title


def build_ledger() -> dict[str, Any]:
    image_dir = REPO_ROOT / "data" / "page_images"
    metadata_path = REPO_ROOT / "data" / "embeddings" / "metadata.json"
    docs_dir = REPO_ROOT / "data" / "docs"

    images = _image_prefix_counts(image_dir)
    metadata_rows, metadata_counts = _metadata_prefix_counts(metadata_path)

    active_rows = [
        {
            "prefix": prefix,
            "page_images": images.get(prefix, 0),
            "embedding_rows": metadata_counts.get(prefix, 0),
            "status": "active_legacy"
            if images.get(prefix, 0) == metadata_counts.get(prefix, 0)
            and images.get(prefix, 0) > 0
            else "mismatch",
        }
        for prefix in ACTIVE_LEGACY_PREFIXES
    ]

    current_rows: list[dict[str, Any]] = []
    if docs_dir.exists():
        for doc_dir in sorted(p for p in docs_dir.iterdir() if p.is_dir()):
            pdf = doc_dir / "source.pdf"
            current_rows.append(
                {
                    "doc_hash": doc_dir.name,
                    "title": _first_doc_title(doc_dir / "parsed.json"),
                    "pages_jsonl": _count_lines(doc_dir / "pages.jsonl"),
                    "chunks": _count_lines(doc_dir / "chunks.jsonl"),
                    "sections": _count_lines(doc_dir / "sections.jsonl"),
                    "page_images": images.get(doc_dir.name, 0),
                    "pdf_mb": round(pdf.stat().st_size / 1024 / 1024, 2) if pdf.exists() else None,
                }
            )

    orphan_prefixes = [prefix for prefix in sorted(images) if prefix not in ACTIVE_LEGACY_PREFIXES]

    return {
        "active_corpus_version": "legacy-visual-738",
        "generated_by": "scripts/corpus_ledger.py",
        "summary": {
            "page_images_total": sum(images.values()),
            "legacy_embedding_rows": len(metadata_rows),
            "legacy_active_rows": sum(metadata_counts[prefix] for prefix in ACTIVE_LEGACY_PREFIXES),
            "current_docs_dirs": len(current_rows),
            "current_docs_pages_jsonl_total": sum(row["pages_jsonl"] for row in current_rows),
            "orphan_image_prefixes": orphan_prefixes,
        },
        "active_legacy_rows": active_rows,
        "current_pipeline_rows": current_rows,
    }


def write_ledger(ledger: dict[str, Any]) -> None:
    docs_dir = REPO_ROOT / "docs"
    docs_dir.mkdir(exist_ok=True)
    (docs_dir / "corpus_ledger.json").write_text(json.dumps(ledger, indent=2) + "\n")

    lines = [
        "# Corpus Ledger — Urban RAG\n",
        "Generated by `scripts/corpus_ledger.py`. This reconciles the old visual corpus "
        "with the current April ingest pipeline.\n",
        "## Summary\n",
    ]
    for key, value in ledger["summary"].items():
        lines.append(f"- **{key}:** `{value}`")

    lines.extend(
        [
            "\n## Active legacy visual corpus\n",
            "| prefix | page images | embedding rows | status |",
            "|---|---:|---:|---|",
        ]
    )
    for row in ledger["active_legacy_rows"]:
        lines.append(
            f"| `{row['prefix']}` | {row['page_images']} | "
            f"{row['embedding_rows']} | {row['status']} |"
        )

    lines.append(
        "\n**Interpretation:** `data/embeddings/metadata.json` has 738 rows: "
        "447 `urdpfi_vol1`, 250 `urdpfi_vol2`, and 41 `swm_2016`. "
        "The user shorthand was “738 URDPFI pages”; locally the 738-row legacy corpus includes "
        "697 URDPFI pages plus 41 SWM pages. If v1 must be strictly URDPFI-only, active "
        "page count is 697. If we preserve the old Lightning corpus exactly, active page "
        "count is 738.\n"
    )

    lines.extend(
        [
            "## Current April pipeline corpus\n",
            "| doc hash | title / first text | pages.jsonl | chunks | sections | "
            "page images | source PDF MB |",
            "|---|---|---:|---:|---:|---:|---:|",
        ]
    )
    for row in ledger["current_pipeline_rows"]:
        title = row["title"].replace("|", "/")
        lines.append(
            f"| `{row['doc_hash'][:8]}…` | {title} | {row['pages_jsonl']} | {row['chunks']} | "
            f"{row['sections']} | {row['page_images']} | {row['pdf_mb']} |"
        )

    lines.extend(
        [
            "\n## Mismatch diagnosis\n",
            "- `data/page_images/` contains 743 PNGs: 738 legacy images + 5 "
            "test/current-pipeline images under a hash prefix.",
            "- `data/embeddings/metadata.json` contains 738 rows matching the legacy "
            "prefixes exactly.",
            "- `urban_rag.cli corpus stats` reports 325 pages from the current April "
            "pipeline manifest/docs path, not the legacy visual corpus.",
            "- Most current `data/docs/*/pages.jsonl` rows have blank `image_uri`, so "
            "current ingest state is not ready for visual retrieval without rerender/reconcile.",
            "- v1 should use the legacy visual corpus as the starting active corpus, then "
            "rebuild a clean versioned Qdrant index from those 738 rows or a strict "
            "697-page URDPFI subset.",
        ]
    )

    (docs_dir / "corpus_ledger.md").write_text("\n".join(lines) + "\n")


def main() -> None:
    ledger = build_ledger()
    write_ledger(ledger)
    import sys

    sys.stdout.write(json.dumps(ledger["summary"], indent=2) + "\n")


if __name__ == "__main__":
    main()
